### ISSUE TITLE
平台碰到线段一次再开启就会穿墙

### ISSUE THREAD

**Issue by ChrisMa130** [ChrisMa130/Game#156]
2-1 关卡最后一个谜题：

STEP 1：这么画一个线段
![image](https://cloud.githubusercontent.com/assets/17721885/19500983/bce55232-9556-11e6-9109-f46403d61c8e.png)

STEP 2：开启机关
![image](https://cloud.githubusercontent.com/assets/17721885/19501015/f70f1bd2-9556-11e6-8241-1ea3227dbd3e.png)

STEP 3：会这样（还没出问题）
![image](https://cloud.githubusercontent.com/assets/17721885/19501033/16a1d16a-9557-11e6-914e-e61d883e190e.png)

STEP 4：开启机关，**在按下机关的一瞬间取消线段**
![image](https://cloud.githubusercontent.com/assets/17721885/19501052/3f0b7e94-9557-11e6-8993-f4808f6d58a5.png)
就会出现BUG

**Comment by jlu3389** [comment]
11c8ee738ee3a38e5fbe66e194562f4dd5e7161b
