### ISSUE TITLE
玩家死了以后游戏会在“暂停”的UI的位置提示按空格能重生

### ISSUE THREAD

**Issue by ChrisMa130** [ChrisMa130/Game#159]
按空格需要能重生，同时游戏会在平时显示暂停的地方提醒玩家能重生。（这个文字可以由我来修改，或者直接就写"Press Space to reset from last checkpoint"）

**Comment by jlu3389** [comment]
已修改为空格后返回上一个检查点

**Comment by ChrisMa130** [comment]
并未修复

**Comment by ChrisMa130** [comment]
我改好了
