### ISSUE TITLE
人爬梯子后时间倒退中阻挡自己就会BUG

### ISSUE THREAD

**Issue by ChrisMa130** [ChrisMa130/Game#160]
![image](https://cloud.githubusercontent.com/assets/17721885/20371987/12d90f12-ac1d-11e6-879b-31a12e71f7a3.png)
 可以用3-1测试，
STEP 1： 
爬梯子下去
![image](https://cloud.githubusercontent.com/assets/17721885/20372000/22c221a2-ac1d-11e6-8b98-2e43e9733e85.png)

STEP2:
![image](https://cloud.githubusercontent.com/assets/17721885/20372009/2cfb3848-ac1d-11e6-867f-76b994e6ff9b.png)
 下到底后在这里阻挡自己
STEP3:
时间倒退到爬梯子的时间。。。就BUG了。。。

**Comment by jlu3389** [comment]
就什么样的bug。。。

**Comment by jlu3389** [comment]
be56bd01e26084c775c21176318632007fe57d36
