### ISSUE TITLE
时间倒退倒退位置的BUG

### ISSUE THREAD

**Issue by ChrisMa130** [ChrisMa130/Game#162]
![image](https://cloud.githubusercontent.com/assets/17721885/20389337/08db250c-ac7e-11e6-91fb-d7a48123ff8c.png)
3-1 正常方法到这里后

STEP1: 先按F恢复时间
![image](https://cloud.githubusercontent.com/assets/17721885/20389347/1adca1b8-ac7e-11e6-94dd-a5d142448262.png)
STEP2: 按住Q一直倒退时间到底，就会产生BUG，人物 跑到这里来了：
![image](https://cloud.githubusercontent.com/assets/17721885/20389370/2c82e076-ac7e-11e6-9067-17e1c1f62608.png)

**Comment by jlu3389** [comment]
8b09c6c22e0039e67ec66240a1559af1d1020ace
